[package]
name = "rust_reml_hello_world"
version = "0.0.0"
authors = ["khai96_ <hvksmr1996@gmail.com>"]
edition = "2018"

[dependencies]
gtk = "^0.5.0"
relm = "^0.15.0"
relm-derive = "^0.15.0"
relm-attributes = "^0.15.0"
